name: Deploy to AWS EKS (production)

on:
  workflow_dispatch:

env:
  PROJECT_NAME: copilot
  PYTHON_VERSION: "3.11.2"

jobs:
  deploy_to_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE_PRODUCTION }}

      - name: Deploy Helm chart to AWS EKS
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: ${{ vars.AWS_REGION }}
          cluster-name: dema-ai-production
          chart-path: k8s-helm
          name: ${{ env.PROJECT_NAME }}
          namespace: prod
          values: env=prod,image.repository=${{ vars.AWS_ECR_REGISTRY }}/${{ env.PROJECT_NAME }},image.tag=${{ github.sha }}
          # values: env=prod,image.repository=${{ vars.AWS_ECR_REGISTRY }}/${{ env.PROJECT_NAME }},image.tag=${{ github.sha }},S3_ACC_KEY=${{ secrets.S3_ACC_KEY_PROD }},S3_SEC_ACC_KEY=${{ secrets.S3_SEC_ACC_KEY_PROD }},slack.bot.token=${{ secrets.SLACK_REPLAY_BOT_TOKEN }}
          # config-files: k8s-helm/values.production.yaml
